language: node_js

node_js:
  - 8
  - 9
  - 10
  - 11
  - 12

before_install: npm i -g npm@latest

cache:
  npm: false

install:
  - npm install --save-dev nyc
  - npm install --save-dev mocha
  - npm install -save-dev chai
script:
  - npm run coverage